sonar.projectKey=griswaldbrooks_cat-detector
sonar.organization=griswaldbrooks
sonar.projectName=cat-detector
sonar.projectVersion=1.0.0
sonar.sources=src/
sonar.coverageReportPaths=sonar-coverage.xml
sonar.exclusions=target/**,models/**,onnxruntime/**,test_images/**,website/**,scripts/**
sonar.sourceEncoding=UTF-8
